# Generated by Django 5.0 on 2023-12-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='call_sign',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
