# Generated by Django 5.0 on 2023-12-11 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport', '0003_airplane_call_sign'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['seat']},
        ),
        migrations.RenameField(
            model_name='airplane',
            old_name='rows',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='airplane',
            name='seats_in_row',
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('flight', 'seat')},
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='row',
        ),
    ]
